# Generated by Django 5.0.3 on 2024-03-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_method',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.TextField(),
        ),
    ]
